[package]
name = "syndicate-obsidian-canvas"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
notify = "8.2.0"
syndicate-json-canvas-lib = { path = "syndicate-json-canvas-lib" }
