[package]
name = "syndicate-obsidian-canvas"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
notify-debouncer-mini = "0.5.0"
syndicate-json-canvas-lib = { path = "syndicate-json-canvas-lib" }
